[RC] 0.9.2: Docker support, minor fixes, and update coin assets/icons
KomodoPlatform/komodo-wallet-mobile pull request #162
Opened 2024-12-19 17:46 UTC by CharlVS

# Changelog

TODO

2024-12-24 19:56 UTC, DeckerSU reviewed
LGTM from a security perspective.

2024-12-24 19:57 UTC, DeckerSU approved these changes
LGTM from a security perspective.

2024-12-27 06:06 UTC, smk762 commented
Docker builds not working in this branch, but will be fixed once https://github.com/KomodoPlatform/komodo-wallet-mobile/pull/156 is merged.

PEPE native logo is https://github.com/KomodoPlatform/coins/blob/master/icons_original/pepe.png
PEPE-ERC20 and other networks token are using https://github.com/KomodoPlatform/coins/blob/master/icons_original/pep.png

I'm unsure if this is intended?

Testing otherwise successful.

2025-01-28 00:30 UTC, smk762 commented
Updated https://github.com/KomodoPlatform/komodo-wallet-mobile/wiki/Project-Setup#build-with-docker to include docker build steps

2025-01-28 00:45 UTC, smk762 requested changes
- Docker builds are now functional. I've updated https://github.com/KomodoPlatform/komodo-wallet-mobile/wiki/Project-Setup#build-with-docker to include the docker build steps. 
- PEPE icons present, though still different for tokens as mentioned in previous comment.
- Confirmed the DEX view is not present.
- swiping right on a funded coin still show the "SWAP" option from portfolio. Clicking on it links to the orderbook. IMO this button should not be visible.
- Orderbook is still present and functional. Seems incongruent with the DEX functionality being removed. IMO, orderbook should also be hidden.

2025-01-28 14:09 UTC, takenagain commented
> * PEPE icons present, though still different for tokens as mentioned in previous comment.

@smk762 The current [icon resolver function](https://github.com/KomodoPlatform/komodo-wallet-mobile/blob/5f849c34b5481957fad31bf613974b089b208d6c/lib/utils/utils.dart#L86) splits the `coin` field by the dash "-", so `PEPE-BEP20` resolves to [pepe.png](https://github.com/KomodoPlatform/coins/blob/master/icons_original/pepe.png) and `PEP` to [pep.png](https://github.com/KomodoPlatform/coins/blob/master/icons_original/pep.png). This issue is also present on the current web release (similar logic is used to resolve the icon name).

Is there another field or approach that should be used? We could modify the icon paths in this repository, but on the web release most assets are downloaded from the GitHub CDN at runtime, so the issue won't be resolved there.

2025-01-28 14:24 UTC, cipig commented
what's the problem with that? it works as it should
PEP and PEPE are 2 different coins,
PEPE is the token https://www.coingecko.com/en/coins/pepe
PEP is the coin https://www.coingecko.com/en/coins/pepecoin-network
they once had similar icons, but now have more distinct ones after old pep.png was replaced with a new one in some PR to coins repoo
you just need to update/use the icons as they are in the coins repo:
PEP: https://github.com/cipig/coins/blob/nogeo/icons/pep.png
PEPE: https://github.com/cipig/coins/blob/nogeo/icons/pepe.png

2025-01-28 17:04 UTC, CharlVS commented
> what's the problem with that? it works as it should PEP and PEPE are 2 different coins, PEPE is the token https://www.coingecko.com/en/coins/pepe PEP is the coin https://www.coingecko.com/en/coins/pepecoin-network they once had similar icons, but now have more distinct ones after old pep.png was replaced with a new one in some PR to coins repoo you just need to update/use the icons as they are in the coins repo: PEP: https://github.com/KomodoPlatform/coins/blob/master/icons/pep.png PEPE: https://github.com/KomodoPlatform/coins/blob/master/icons/pepe.png

@smk762 I'm tagging you since the above is addressed to you

2025-01-29 03:58 UTC, smk762 commented
Thanks for the confirmation

2025-01-29 13:18 UTC, AndrewDelaney requested changes
There is an issue with the password validation messages, as well as with the validation itself. I am able to create a password without using any numbers. All other input characters are validated correctly, it just seems to be the numbers that are disregarded. The password validation messages disappear as soon as I meet the uppercase char, lowercase char, special char and length requirements. And then it allows me to proceed in creating the wallet (albeit seems to load into infinity until I close the app down and log in again)

Logged issue: https://github.com/KomodoPlatform/komodo-wallet-mobile/issues/168

2025-02-13 13:23 UTC, merged